### ISSUE TITLE
Date management

### ISSUE THREAD

**Issue by VeryTastyTomato** [flowerkinzy/GaliDAV-Autonomy#10]
I am reading the code written, but I don’t understand how dates are managed, and it’s not visible on the current interface. Can someone explain briefly where they are?

**Comment by flowerkinzy** [comment]
Je comprends,quelles dates: dates des objets cours, dates des cours dans la BDD, dates entrées dans le form, semaine affichée?

Dans quel but?

**Comment by VeryTastyTomato** [comment]
La semaine affichée. Ou plutôt, je ne vois pas de calendrier au sens où il n’y a pas les jours et les mois de l’année.

**Comment by flowerkinzy** [comment]
pour l'instant, il n'y a pas de trigger sur les boutons préc & suivants mais par défaut le calendrier affiche les évènements de la semaine du 14 sept (var FIRST_DAY_OF_WEEK_UTC).

Si tu crées un cours en dur qui n'est pas sûr cette semaine, il n'est pas affiché. On a que des vues semaines

Et du coup, la 1ère ligne devrait être actualisée pour afficher des cellules du type "Lundi 14/09"

**Comment by VeryTastyTomato** [comment]
Ça veut dire qu’on gère nous-mêmes les dates ? Comment ça se passe quand on change d’année ? Parce que gérer par nous-mêmes les dates est, à mon avis, strictement impossible.

**Comment by flowerkinzy** [comment]
Réponse courte oui. Réponse développée: Réunion de ce matin
