### ISSUE TITLE
Form new Event (horaires)

### ISSUE THREAD

**Issue by flowerkinzy** [flowerkinzy/GaliDAV-Autonomy#12]
Contrôler le format des horaires (juste après qu'on perd le focus):
   -vérifier que c un chiffre 
 -vérifier que c un multiple de 15

**Comment by Orni2Thorinque** [comment]
Et ça fait quoi après la vérification? Un dialog qui dit que c'est erroné?

**Comment by Orni2Thorinque** [comment]
Oubliez, c'est une mauvaise idée.

**Comment by flowerkinzy** [comment]
juste après l'entrée, (avant même d'arriver au bouton d'envoi)

**Comment by Orni2Thorinque** [comment]
ça met le champ en rouge maintenant pour les heures et les minutes non supportées.

**Comment by flowerkinzy** [comment]
Merci, je viens de tester en effet, cet aspect est ok mais il prend aussi le texte pour des chiffres. Et il faut bloquer la validation. Je m'en occupe
