### ISSUE TITLE
Un aperçu d'un calendrier fait uniquement par le client

### ISSUE THREAD

**Issue by flowerkinzy** [flowerkinzy/GaliDAV-Autonomy#14]
![bref](https://cloud.githubusercontent.com/assets/8625370/9648057/257d6af8-51e4-11e5-974f-72764b500cb1.png)

**Comment by LilTiti** [comment]
Tu n'as utilisé que l'interface de GaliDAV et l'admin panel ?

**Comment by flowerkinzy** [comment]
oui

**Comment by flowerkinzy** [comment]
Ah j'ai oublié @LilTiti  @Orni2Thorinque  @VeryTastyTomato , parfois en bidouillant pour des tests, je change les valeurs id default en en-tête de calendar.js (En général, elle doivent être à 1), vu que les id commencent à 1
