### ISSUE TITLE
Plusieurs vues ?

### ISSUE THREAD

**Issue by LilTiti** [flowerkinzy/GaliDAV-Autonomy#5]
J'ai vu que pour le moment on a gardé le principe d'agendav à proposer plusieurs vues d'emplois du temps (day/week/month), est-ce vraiment utile ? Je pense qu'on doit être dans un processus d'allègement maximal du travail, et par conséquent de supprimer toute chose non essentielle. Même si ce travail me parait à première vue léger, je pense qu'il n'est pas essentiel et doit donc être enlevé pour le moment.

**Comment by flowerkinzy** [comment]
Oui, en fait je pense que Simon a repris le layout tel quel. Pour ma part, jai commenté cette partie
