### ISSUE TITLE
Bootstrap ?

### ISSUE THREAD

**Issue by LilTiti** [flowerkinzy/GaliDAV-Autonomy#6]
Encore une proposition, mais beaucoup moins risquée que Symfony cette fois : l'utilisation de Bootstrap. Quelqu'un le connait-il ? Ce n'est qu'en somme qu'un fichier CSS bourré de règles qui fait une grosse partie du style pour nous, nous n'avons presque qu'à assigner certaines classes à nos éléments html et c'est beau.

**Comment by flowerkinzy** [comment]
Non, mais pourquoi pas. Pour certains widgets ( du genre form new Event), il ya du thème jQuery  (donc à ne surtout pas toucher!) mais en effet, il faut peaufiner pour le reste.

Est-ce que @Orni2Thorinque le connaît, puisqu'il a fait les menus en CSS?

**Comment by LilTiti** [comment]
Je vais faire une branche Bootstrap pour faire le visu avec, et pour garder une version actuelle au cas où quelque chose ne va pas. Je le fais de suite

**Comment by LilTiti** [comment]
Et si tout va bien on pourra merge

**Comment by flowerkinzy** [comment]
OK. (Attention au merge sur console vs pull sur git, je me suis bien embrouilée pour revenir après)

**Comment by LilTiti** [comment]
Pourquoi c'est quoi le pb ?

**Comment by flowerkinzy** [comment]
c pas un pb en fait j'ai fait un pull request sur github que j'ai accepté mais après sur ma console quand je voulais revenir sur master, je me suis embrouillée les pédales et j'ai failli perdre des modifs

Je pense que j'ai dû loupé une étape dans le commandes, c tout

**Comment by flowerkinzy** [comment]
Insertion et Structure des menus par Simon, identité graphique et dynamisme par Etienne, ça commence à bien rendre.
