### ISSUE TITLE
Background gradient

### ISSUE THREAD

**Issue by flowerkinzy** [flowerkinzy/GaliDAV-Autonomy#7]
Il y a un backround de type gradient sur quelques objets(html,body, et cellules de calendriers par ex).
Est-il possible de rendre cela cross-browser. (Ex: Je suis sur firefox à la maison et ça n'a rien avoir avec mon chrome du stage).

**Comment by LilTiti** [comment]
Je n'utilise que Firefox partout donc je ne vois pas la différence...

**Comment by VeryTastyTomato** [comment]
L’attribut `-moz-linear-gradient` est utilisé dans le fichier `style/styles.css`, le « moz » indique que c’est pour Firefox seulement. C’est pas un attribut standard il faut donc le supprimer.

**Comment by flowerkinzy** [comment]
Justement, je veux que ça marche partout.
Pcq linear marche pas partout

**Comment by LilTiti** [comment]
Si je peux me permettre, je pense qu'il ne faut pas rester sur des détails de style avant que j'ai fini ma branche sur Bootstrap, étant donné qu'il assigne lui-même beaucoup de règles..

**Comment by flowerkinzy** [comment]
ok
